# Generated by Django 3.2.16 on 2022-11-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='linkedin',
        ),
    ]
