# Generated by Django 3.2.16 on 2022-11-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_auto_20221121_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='mycv',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='skill',
        ),
    ]
