# Generated by Django 3.2.16 on 2022-11-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_auto_20221121_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
